// packages/react/src/index.tsx
import { formatSemanticFallback, getLifecycleTargets, resolveChatSession, resolveChatTheme, resolveChoiceAction, resolveChoiceListFrame, selectChoice } from '@agentskit/chat'
import type { ChatDefinition, ChatSession, ChatTheme, ChatThemeInput, ComponentManifest } from '@agentskit/chat'
import { decodeComponentFrame, isComponentFrameCandidate } from '@agentskit/chat-protocol'
import type { ComponentSelectionEvent } from '@agentskit/chat-protocol'
import {
  ChatContainer,
  InputBar,
  Message,
  ThinkingIndicator,
  ToolConfirmation,
  useChat,
} from '@agentskit/react'
import { useMemo, useRef, useState, type ComponentProps, type ComponentType, type CSSProperties, type ReactElement } from 'react'

export type ChatCssVariables = CSSProperties & { readonly [key: `--ak-${string}`]: string | number }

export const toChatCssVariables = (input?: ChatThemeInput): ChatCssVariables => {
  const theme = resolveChatTheme(input)
  return {
    '--ak-color-bg': theme.colors.background,
    '--ak-color-surface': theme.colors.surface,
    '--ak-color-border': theme.colors.border,
    '--ak-color-text': theme.colors.text,
    '--ak-color-text-muted': theme.colors.muted,
    '--ak-color-bubble-user': theme.colors.accent,
    '--ak-color-bubble-user-text': theme.colors.onAccent,
    '--ak-color-bubble-assistant': theme.colors.surface,
    '--ak-color-bubble-assistant-text': theme.colors.text,
    '--ak-color-input-bg': theme.colors.background,
    '--ak-color-input-border': theme.colors.border,
    '--ak-color-input-focus': theme.colors.accent,
    '--ak-color-button': theme.colors.accent,
    '--ak-color-button-text': theme.colors.onAccent,
    '--ak-color-tool-bg': theme.colors.surface,
    '--ak-color-tool-border': theme.colors.border,
    '--ak-app-color-danger': theme.colors.danger,
    '--ak-font-family': theme.fontFamily === 'system' ? "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif" : theme.fontFamily,
    '--ak-radius': `${theme.radius.medium}px`,
    '--ak-radius-lg': `${theme.radius.large}px`,
    '--ak-spacing-sm': `${theme.spacing.small}px`,
    '--ak-spacing-md': `${theme.spacing.medium}px`,
    '--ak-spacing-lg': `${theme.spacing.large}px`,
  }
}

export interface AgentChatSlots {
  readonly Container?: ComponentType<ComponentProps<typeof ChatContainer>>
  readonly Message?: ComponentType<ComponentProps<typeof Message>>
  readonly Input?: ComponentType<ComponentProps<typeof InputBar>>
  readonly Thinking?: ComponentType<ComponentProps<typeof ThinkingIndicator>>
  readonly Confirmation?: ComponentType<ComponentProps<typeof ToolConfirmation>>
  readonly ChoiceList?: ComponentType<ChoiceListProps>
}

export interface AgentChatProps {
  readonly definition: ChatDefinition
  readonly placeholder?: string
  readonly onComponentSelect?: (event: ComponentSelectionEvent) => void
  readonly actionConfirmationTtlMs?: number
  readonly session?: ChatSession
  readonly theme?: ChatThemeInput
  readonly slots?: AgentChatSlots
}

export interface ChoiceListProps {
  readonly frame: unknown
  readonly manifest: ComponentManifest
  readonly onSelect: (event: ComponentSelectionEvent) => void
  readonly disabled?: boolean
}

export const ChoiceList = ({ frame, manifest, onSelect, disabled = false }: ChoiceListProps): ReactElement | null => {
  const resolved = resolveChoiceListFrame(frame, manifest)
  if (!resolved.ok) return null
  return (
    <fieldset aria-label={resolved.props.prompt} data-ak-component="choice-list">
      <legend>{resolved.props.prompt}</legend>
      {resolved.props.choices.map(choice => (
        <button key={choice.id} type="button" disabled={disabled} onClick={() => onSelect(selectChoice(resolved.frame, choice.id))}>
          <span>{choice.label}</span>
          {choice.description === undefined ? null : <small>{choice.description}</small>}
        </button>
      ))}
    </fieldset>
  )
}

const AgentChatSession = ({ definition, placeholder, onComponentSelect = () => undefined, actionConfirmationTtlMs, session: preparedSession, theme: themeInput, slots = {} }: AgentChatProps): ReactElement => {
  const theme: ChatTheme = resolveChatTheme(themeInput)
  const ContainerSlot = slots.Container ?? ChatContainer
  const MessageSlot = slots.Message ?? Message
  const InputSlot = slots.Input ?? InputBar
  const ThinkingSlot = slots.Thinking ?? ThinkingIndicator
  const ConfirmationSlot = slots.Confirmation ?? ToolConfirmation
  const ChoiceListSlot = slots.ChoiceList ?? ChoiceList
  const [session] = useState(() => resolveChatSession(definition, preparedSession))
  const sessionId = session.sessionId
  const [actionError, setActionError] = useState<Error | undefined>()
  const [editDraft, setEditDraft] = useState<{ readonly messageId: string, readonly content: string }>()
  const [resolvedInstances, setResolvedInstances] = useState<ReadonlySet<string>>(() => new Set())
  const resolvedInstancesRef = useRef(new Set<string>())
  const config = useMemo(() => session.updateChat(definition.chat), [definition.chat, session])
  const chat = useChat(config)
  const chatRef = useRef(chat)
  chatRef.current = chat
  const [confirmation] = useState(() => session.createConfirmation({ ...(actionConfirmationTtlMs === undefined ? {} : { ttlMs: actionConfirmationTtlMs }), chat: {
    proposeToolCall: proposal => chatRef.current.proposeToolCall(proposal),
    approve: id => chatRef.current.approve(id),
    deny: (id, reason) => chatRef.current.deny(id, reason),
  } }))
  const selectComponent = (event: ComponentSelectionEvent, frame: import('@agentskit/chat-protocol').ComponentRenderFrame): void => {
    if (resolvedInstancesRef.current.has(event.instanceId)) return
    setActionError(undefined)
    resolvedInstancesRef.current.add(event.instanceId)
    setResolvedInstances(new Set(resolvedInstancesRef.current))
    try { onComponentSelect(event) } catch (error) {
      setActionError(error instanceof Error ? error : new Error('Component selection callback failed.'))
    }
    const action = resolveChoiceAction(frame, event.choiceId)
    if (action) void confirmation.propose(action).catch(error => {
      resolvedInstancesRef.current.delete(event.instanceId)
      setResolvedInstances(new Set(resolvedInstancesRef.current))
      setActionError(error instanceof Error ? error : new Error('Action proposal failed.'))
    })
  }
  const approve = (toolCallId: string): void => {
    const record = confirmation.getByToolCall(toolCallId)
    void (record ? confirmation.approve(record.token, sessionId) : chat.approve(toolCallId)).catch(error => setActionError(error instanceof Error ? error : new Error('Action approval failed.')))
  }
  const deny = (toolCallId: string, reason?: string): void => {
    const record = confirmation.getByToolCall(toolCallId)
    void (record ? confirmation.reject(record.token, sessionId, reason) : chat.deny(toolCallId, reason)).catch(error => setActionError(error instanceof Error ? error : new Error('Action rejection failed.')))
  }
  const targets = getLifecycleTargets(chat.messages)
  const runLifecycle = (operation: Promise<void>): void => {
    setActionError(undefined)
    void operation.catch(error => setActionError(error instanceof Error ? error : new Error('Lifecycle operation failed.')))
  }

  return (
    <section aria-label={`${definition.id} chat`} data-ak-app-chat="" style={themeInput === undefined ? undefined : toChatCssVariables(theme)}>
      <div aria-live="polite" aria-relevant="additions text" role="log">
        <ContainerSlot>
          {chat.messages.map(message => {
            const candidate = message.role === 'assistant' && isComponentFrameCandidate(message.content)
            const decoded = candidate ? decodeComponentFrame(message.content) : undefined
            if (decoded?.ok) {
              const resolved = definition.components === undefined
                ? undefined
                : resolveChoiceListFrame(decoded.frame, definition.components)
              return resolved?.ok
                ? <ChoiceListSlot key={message.id} frame={decoded.frame} manifest={definition.components!} disabled={resolvedInstances.has(decoded.frame.instanceId)} onSelect={event => selectComponent(event, decoded.frame)} />
                : <p key={message.id} data-ak-component-fallback="">{formatSemanticFallback(decoded.frame.fallback)}</p>
            }
            if (decoded && !decoded.ok) return <p key={message.id} role="alert" data-ak-component-diagnostic={decoded.diagnostic.code}>{decoded.diagnostic.message}</p>
            return <MessageSlot key={message.id} message={message} />
          })}
          {chat.messages.flatMap(message => message.toolCalls ?? []).map(toolCall => (
            <ConfirmationSlot key={toolCall.id} toolCall={toolCall} onApprove={approve} onDeny={deny} />
          ))}
          <ThinkingSlot visible={chat.status === 'streaming'} />
        </ContainerSlot>
      </div>
      {chat.error || actionError ? <p role="alert" style={{ color: theme.colors.danger }}>{chat.error?.message ?? actionError?.message}</p> : null}
      {chat.status === 'streaming' ? <button type="button" onClick={chat.stop}>Stop</button> : null}
      {chat.status !== 'streaming' && targets.userId ? (
        <div aria-label="Response actions">
          <button type="button" aria-label="Retry response" onClick={() => runLifecycle(chat.retry())}>Retry</button>
          {targets.assistantId ? <button type="button" aria-label="Regenerate response" onClick={() => runLifecycle(chat.regenerate(targets.assistantId))}>Regenerate</button> : null}
          <button type="button" onClick={() => setEditDraft({ messageId: targets.userId!, content: chat.messages.find(message => message.id === targets.userId)?.content ?? '' })}>Edit last message</button>
          {editDraft === undefined ? null : (
            <form onSubmit={event => {
              event.preventDefault()
              if (editDraft.content.trim() === '') return
              runLifecycle(chat.edit(editDraft.messageId, editDraft.content))
              setEditDraft(undefined)
            }}>
              <label>Edit message<input aria-label="Edit message" value={editDraft.content} onChange={event => setEditDraft({ ...editDraft, content: event.target.value })} /></label>
              <button type="submit" aria-label="Save edit">Save edit</button>
              <button type="button" onClick={() => setEditDraft(undefined)}>Cancel edit</button>
            </form>
          )}
        </div>
      ) : null}
      <InputSlot
        chat={chat}
        disabled={chat.status === 'streaming'}
        {...(placeholder === undefined ? {} : { placeholder })}
      />
    </section>
  )
}

export const AgentChat = (props: AgentChatProps): ReactElement => (
  <AgentChatSession key={`${props.definition.id}:${props.definition.revision ?? 1}:${props.session?.sessionId ?? 'new'}`} {...props} />
)

export type { ChatDefinition } from '@agentskit/chat'

// packages/solid/src/index.tsx
import { formatSemanticFallback, getLifecycleTargets, resolveChatSession, resolveChatTheme, resolveChoiceAction, resolveChoiceListFrame, selectChoice } from '@agentskit/chat'
import type { ChatDefinition, ChatSession, ChatThemeInput, ComponentManifest } from '@agentskit/chat'
import { decodeComponentFrame, isComponentFrameCandidate } from '@agentskit/chat-protocol'
import type { ComponentRenderFrame, ComponentSelectionEvent } from '@agentskit/chat-protocol'
import { ChatContainer, InputBar, Message, ThinkingIndicator, ToolConfirmation, useChat } from '@agentskit/solid'
import type { ChatReturn, Message as ChatMessage, ToolCall } from '@agentskit/core'
import { For, Show, createEffect, createMemo, createSignal, on, untrack, type JSX } from 'solid-js'

export type ChatCssVariables = JSX.CSSProperties & { readonly [key: `--ak-${string}`]: string | number }
export const toChatCssVariables = (input?: ChatThemeInput): ChatCssVariables => {
  const theme = resolveChatTheme(input)
  return {
    '--ak-color-bg': theme.colors.background, '--ak-color-surface': theme.colors.surface, '--ak-color-border': theme.colors.border,
    '--ak-color-text': theme.colors.text, '--ak-color-text-muted': theme.colors.muted, '--ak-color-bubble-user': theme.colors.accent,
    '--ak-color-bubble-user-text': theme.colors.onAccent, '--ak-color-bubble-assistant': theme.colors.surface, '--ak-color-bubble-assistant-text': theme.colors.text,
    '--ak-color-input-bg': theme.colors.background, '--ak-color-input-border': theme.colors.border, '--ak-color-input-focus': theme.colors.accent,
    '--ak-color-button': theme.colors.accent, '--ak-color-button-text': theme.colors.onAccent, '--ak-color-tool-bg': theme.colors.surface,
    '--ak-color-tool-border': theme.colors.border, '--ak-app-color-danger': theme.colors.danger,
    '--ak-font-family': theme.fontFamily === 'system' ? "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif" : theme.fontFamily,
    '--ak-radius': `${theme.radius.medium}px`, '--ak-radius-lg': `${theme.radius.large}px`, '--ak-spacing-sm': `${theme.spacing.small}px`,
    '--ak-spacing-md': `${theme.spacing.medium}px`, '--ak-spacing-lg': `${theme.spacing.large}px`,
  }
}

export interface ChoiceListProps { readonly frame: unknown; readonly manifest: ComponentManifest; readonly onSelect: (event: ComponentSelectionEvent) => void; readonly disabled?: boolean }
export function ChoiceList(props: ChoiceListProps): JSX.Element {
  const resolved = createMemo(() => resolveChoiceListFrame(props.frame, props.manifest))
  return <Show when={resolved().ok ? resolved() : undefined}>{value => {
    const item = value() as Extract<ReturnType<typeof resolveChoiceListFrame>, { ok: true }>
    return <fieldset aria-label={item.props.prompt} data-ak-component="choice-list"><legend>{item.props.prompt}</legend><For each={item.props.choices}>{choice =>
      <button type="button" disabled={props.disabled} onClick={() => props.onSelect(selectChoice(item.frame, choice.id))}><span>{choice.label}</span><Show when={choice.description}>{description => <small>{description()}</small>}</Show></button>
    }</For></fieldset>
  }}</Show>
}

export interface AgentChatProps {
  readonly definition: ChatDefinition; readonly placeholder?: string; readonly onComponentSelect?: (event: ComponentSelectionEvent) => void
  readonly actionConfirmationTtlMs?: number; readonly session?: ChatSession; readonly theme?: ChatThemeInput
  readonly container?: (children: JSX.Element) => JSX.Element; readonly message?: (message: ChatMessage) => JSX.Element
  readonly input?: (chat: ChatReturn, disabled: boolean, placeholder?: string) => JSX.Element; readonly thinking?: (visible: boolean) => JSX.Element
  readonly confirmation?: (toolCall: ToolCall, approve: (id: string) => void, deny: (id: string, reason?: string) => void) => JSX.Element
  readonly choiceList?: (props: ChoiceListProps) => JSX.Element
}

function ChatBinding(props: { readonly config: ChatDefinition['chat']; readonly onState: (chat: ChatReturn) => void; readonly children: (chat: ChatReturn) => JSX.Element }): JSX.Element {
  const chat = useChat(props.config)
  createEffect(() => { void chat.status; void chat.messages; props.onState(chat) })
  return props.children(chat)
}

function AgentChatSession(props: AgentChatProps): JSX.Element {
  const initial = untrack(() => ({ definition: props.definition, session: props.session, ttl: props.actionConfirmationTtlMs }))
  const session = resolveChatSession(initial.definition, initial.session)
  const sessionId = session.sessionId
  const [activeChat, setActiveChat] = createSignal(initial.definition.chat)
  let messages = initial.definition.chat.initialMessages ?? []
  const [actionError, setActionError] = createSignal<Error>()
  const [editDraft, setEditDraft] = createSignal<{ readonly messageId: string; readonly content: string }>()
  const [resolvedInstances, setResolvedInstances] = createSignal(new Set<string>())
  let currentChat: ChatReturn | undefined
  const coordinator = session.createConfirmation({
    ...(initial.ttl === undefined ? {} : { ttlMs: initial.ttl }),
    chat: { proposeToolCall: proposal => currentChat!.proposeToolCall(proposal), approve: id => currentChat!.approve(id), deny: (id, reason) => currentChat!.deny(id, reason) },
  })
  createEffect(on(() => props.definition.chat, next => setActiveChat(() => next), { defer: true }))
  const fail = (error: unknown, fallback: string): void => { setActionError(error instanceof Error ? error : new Error(fallback)) }
  const selectComponent = (event: ComponentSelectionEvent, frame: ComponentRenderFrame): void => {
    if (resolvedInstances().has(event.instanceId)) return
    setActionError(); setResolvedInstances(current => new Set(current).add(event.instanceId))
    try { props.onComponentSelect?.(event) } catch (error) { fail(error, 'Component selection callback failed.') }
    const action = resolveChoiceAction(frame, event.choiceId)
    if (action) void coordinator.propose(action).catch(error => { setResolvedInstances(current => { const next = new Set(current); next.delete(event.instanceId); return next }); fail(error, 'Action proposal failed.') })
  }
  const approve = (id: string): void => { const record = coordinator.getByToolCall(id); void (record ? coordinator.approve(record.token, sessionId) : currentChat!.approve(id)).catch(error => fail(error, 'Action approval failed.')) }
  const deny = (id: string, reason?: string): void => { const record = coordinator.getByToolCall(id); void (record ? coordinator.reject(record.token, sessionId, reason) : currentChat!.deny(id, reason)).catch(error => fail(error, 'Action rejection failed.')) }
  const run = (operation: Promise<void>): void => { setActionError(); void operation.catch(error => fail(error, 'Lifecycle operation failed.')) }

  const renderMessage = (item: ChatMessage): JSX.Element => {
    const candidate = item.role === 'assistant' && isComponentFrameCandidate(item.content)
    const decoded = candidate ? decodeComponentFrame(item.content) : undefined
    if (decoded?.ok) {
      const resolved = props.definition.components === undefined ? undefined : resolveChoiceListFrame(decoded.frame, props.definition.components)
      if (resolved?.ok) {
        const choiceProps: ChoiceListProps = { frame: decoded.frame, manifest: props.definition.components!, get disabled() { return resolvedInstances().has(decoded.frame.instanceId) }, onSelect: (event: ComponentSelectionEvent) => selectComponent(event, decoded.frame) }
        return props.choiceList?.(choiceProps) ?? <ChoiceList frame={choiceProps.frame} manifest={choiceProps.manifest} disabled={resolvedInstances().has(decoded.frame.instanceId)} onSelect={choiceProps.onSelect} />
      }
      return <p data-ak-component-fallback>{formatSemanticFallback(decoded.frame.fallback)}</p>
    }
    if (decoded && !decoded.ok) return <p role="alert" data-ak-component-diagnostic={decoded.diagnostic.code}>{decoded.diagnostic.message}</p>
    return props.message?.(item) ?? <Message message={item} />
  }

  const renderChat = (chat: ChatReturn): JSX.Element => {
    currentChat = chat
    const targets = createMemo(() => getLifecycleTargets(chat.messages))
    const content = <><For each={chat.messages}>{renderMessage}</For><For each={chat.messages.flatMap(item => item.toolCalls ?? [])}>{toolCall => props.confirmation?.(toolCall, approve, deny) ?? <ToolConfirmation toolCall={toolCall} onApprove={approve} onDeny={deny} />}</For>{props.thinking?.(chat.status === 'streaming') ?? <ThinkingIndicator visible={chat.status === 'streaming'} />}</>
    return <section aria-label={`${props.definition.id} chat`} data-ak-app-chat style={props.theme === undefined ? undefined : toChatCssVariables(props.theme)}>
      <div aria-live="polite" aria-relevant="additions text" role="log">{props.container?.(content) ?? <ChatContainer>{content}</ChatContainer>}</div>
      <Show when={chat.error ?? actionError()}>{error => <p role="alert" style={{ color: resolveChatTheme(props.theme).colors.danger }}>{error().message}</p>}</Show>
      <Show when={chat.status === 'streaming'}><button type="button" onClick={chat.stop}>Stop</button></Show>
      <Show when={chat.status !== 'streaming' && targets().userId}><div aria-label="Response actions">
        <button type="button" aria-label="Retry response" onClick={() => run(chat.retry())}>Retry</button>
        <Show when={targets().assistantId}>{assistantId => <button type="button" aria-label="Regenerate response" onClick={() => run(chat.regenerate(assistantId()))}>Regenerate</button>}</Show>
        <button type="button" onClick={() => { const id = targets().userId!; setEditDraft({ messageId: id, content: chat.messages.find(item => item.id === id)?.content ?? '' }) }}>Edit last message</button>
        <Show when={editDraft()}>{draft => <form onSubmit={event => { event.preventDefault(); if (!draft().content.trim()) return; run(chat.edit(draft().messageId, draft().content)); setEditDraft() }}>
          <label>Edit message<input aria-label="Edit message" value={draft().content} onInput={event => setEditDraft({ ...draft(), content: event.currentTarget.value })} /></label>
          <button type="submit" aria-label="Save edit">Save edit</button><button type="button" onClick={() => setEditDraft()}>Cancel edit</button>
        </form>}</Show>
      </div></Show>
      {props.input?.(chat, chat.status === 'streaming', props.placeholder) ?? <InputBar chat={chat} disabled={chat.status === 'streaming'} {...(props.placeholder === undefined ? {} : { placeholder: props.placeholder })} />}
    </section>
  }

  return <Show keyed when={activeChat()}>{config => <ChatBinding config={session.updateChat({ ...config, initialMessages: messages })} onState={chat => {
    currentChat = chat
    messages = chat.messages
  }}>{renderChat}</ChatBinding>}</Show>
}

export function AgentChat(props: AgentChatProps): JSX.Element {
  const key = createMemo(() => `${props.definition.id}:${props.definition.revision ?? 1}:${props.session?.sessionId ?? 'new'}`)
  return <Show keyed when={key()}>{_key => <AgentChatSession {...props} />}</Show>
}

export type { ChatDefinition } from '@agentskit/chat'
